In [1]:
import pandas as pd
import pickle
from mlxtend.frequent_patterns import association_rules

## Pattern mining on purchases and different sections

This section of the analysis aims to show the most frequent patterns in purchase products of different sections in the same session. The purpose for this is to show a link to a particular section when the user adds to the basket a product of another section, in order to push the user to buy more products.

In [2]:
with open("frequent_purchase_section_2.pkl", "rb") as f:  # "rb" = read binary
    s_purchases = pickle.load(f)

s_purchases = pd.DataFrame(s_purchases)

print("Number of frequent sections")
print(len(s_purchases))

Number of frequent sections
141

In [3]:
s_purchases_rules = association_rules(s_purchases, metric="confidence", min_threshold=0.3)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum confidence level set to 0.3")
s_purchases_rules

Association rules with minimum confidence level set to 0.3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ computers, accessories})",frozenset({ appliances}),0.005587,0.436083,0.002456,0.439573,1.008003
1,"frozenset({ appliances, accessories})",frozenset({ computers}),0.006463,0.350288,0.002456,0.379981,1.084767
2,"frozenset({ accessories, electronics})",frozenset({ computers}),0.003549,0.350288,0.001193,0.336283,0.960020
3,"frozenset({ accessories, electronics})",frozenset({ appliances}),0.003549,0.436083,0.001278,0.360177,0.825937
4,frozenset({ electronics}),frozenset({ appliances}),0.123306,0.436083,0.040101,0.325218,0.745770
...,...,...,...,...,...,...,...
78,"frozenset({ construction, sport})",frozenset({ computers}),0.007154,0.350288,0.002453,0.342845,0.978752
79,"frozenset({ computers, construction, sport})",frozenset({ appliances}),0.002453,0.436083,0.001482,0.604353,1.385868
80,"frozenset({ construction, appliances, sport})",frozenset({ computers}),0.003332,0.350288,0.001482,0.444863,1.269994
81,"frozenset({ construction, country_yard})",frozenset({ appliances}),0.009069,0.436083,0.005555,0.612535,1.404629
82,"frozenset({ computers, construction, country...",frozenset({ appliances}),0.001765,0.436083,0.001156,0.654804,1.501559

Using confidence as threshold value to determine the best association rules is not so reliable in this situation. This is because there are some sections (particularly "appliances" and "computers") with a really high support. The computation of confidence takes into account only how frequent the antecedent is, causing an inflation of the measure. This can also be seen when looking at the lift, which for some rules is even below 1. This is why, in this situation, is much more better to compute association rules using a minimum lift threshold.

In [4]:
s_purchases_rules = association_rules(s_purchases, metric="lift", min_threshold=2)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum lift level set to 2")
s_purchases_rules

Association rules with minimum lift level set to 2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ computers, sport})","frozenset({ appliances, electronics})",0.039282,0.040101,0.003505,0.089216,2.224763
1,"frozenset({ appliances, sport})","frozenset({ computers, electronics})",0.043367,0.034643,0.003505,0.080811,2.332649
2,"frozenset({ electronics, sport})","frozenset({ computers, appliances})",0.013089,0.104244,0.003505,0.267754,2.568525
3,"frozenset({ computers, appliances})","frozenset({ electronics, sport})",0.104244,0.013089,0.003505,0.033619,2.568525
4,"frozenset({ computers, electronics})","frozenset({ appliances, sport})",0.034643,0.043367,0.003505,0.101160,2.332649
5,"frozenset({ appliances, electronics})","frozenset({ computers, sport})",0.040101,0.039282,0.003505,0.087392,2.224763
6,"frozenset({ furniture, appliances})","frozenset({ computers, sport})",0.017586,0.039282,0.001394,0.079286,2.018392
7,"frozenset({ furniture, sport})","frozenset({ computers, appliances})",0.005618,0.104244,0.001394,0.248183,2.380784
8,"frozenset({ computers, appliances})","frozenset({ furniture, sport})",0.104244,0.005618,0.001394,0.013375,2.380784
9,"frozenset({ computers, sport})","frozenset({ furniture, appliances})",0.039282,0.017586,0.001394,0.035494,2.018392
10,"frozenset({ furniture, computers})","frozenset({ appliances, electronics})",0.017538,0.040101,0.001445,0.082363,2.053888
11,"frozenset({ furniture, appliances})","frozenset({ computers, electronics})",0.017586,0.034643,0.001445,0.082143,2.371093
12,"frozenset({ furniture, electronics})","frozenset({ computers, appliances})",0.005637,0.104244,0.001445,0.256267,2.458333
13,"frozenset({ computers, appliances})","frozenset({ furniture, electronics})",0.104244,0.005637,0.001445,0.013857,2.458333
14,"frozenset({ computers, electronics})","frozenset({ furniture, appliances})",0.034643,0.017586,0.001445,0.041697,2.371093
15,"frozenset({ appliances, electronics})","frozenset({ furniture, computers})",0.040101,0.017538,0.001445,0.036022,2.053888
16,"frozenset({ computers, appliances, electroni...",frozenset({ medicine}),0.016647,0.053695,0.001878,0.112809,2.100902
17,"frozenset({ computers, medicine})","frozenset({ appliances, electronics})",0.016800,0.040101,0.001878,0.111776,2.787338
18,"frozenset({ computers, appliances})","frozenset({ medicine, electronics})",0.104244,0.007675,0.001878,0.018014,2.347185
19,"frozenset({ computers, electronics})","frozenset({ medicine, appliances})",0.034643,0.020741,0.001878,0.054206,2.613408
20,"frozenset({ medicine, appliances})","frozenset({ computers, electronics})",0.020741,0.034643,0.001878,0.090537,2.613408
21,"frozenset({ medicine, electronics})","frozenset({ computers, appliances})",0.007675,0.104244,0.001878,0.244681,2.347185
22,"frozenset({ appliances, electronics})","frozenset({ computers, medicine})",0.040101,0.016800,0.001878,0.046829,2.787338
23,frozenset({ medicine}),"frozenset({ computers, appliances, electroni...",0.053695,0.016647,0.001878,0.034973,2.100902
24,"frozenset({ electronics, sport})",frozenset({ medicine}),0.013089,0.053695,0.001432,0.109405,2.037509
25,frozenset({ medicine}),"frozenset({ electronics, sport})",0.053695,0.013089,0.001432,0.026668,2.037509
26,"frozenset({ computers, medicine})","frozenset({ appliances, sport})",0.016800,0.043367,0.001686,0.100374,2.314514
27,"frozenset({ computers, appliances})","frozenset({ medicine, sport})",0.104244,0.006997,0.001686,0.016177,2.312099
28,"frozenset({ computers, sport})","frozenset({ medicine, appliances})",0.039282,0.020741,0.001686,0.042929,2.069722
29,"frozenset({ medicine, appliances})","frozenset({ computers, sport})",0.020741,0.039282,0.001686,0.081302,2.069722
30,"frozenset({ medicine, sport})","frozenset({ computers, appliances})",0.006997,0.104244,0.001686,0.241023,2.312099
31,"frozenset({ appliances, sport})","frozenset({ computers, medicine})",0.043367,0.016800,0.001686,0.038885,2.314514
32,"frozenset({ appliances, sport})","frozenset({ computers, country_yard})",0.043367,0.017520,0.001963,0.045257,2.583230
33,"frozenset({ computers, country_yard})","frozenset({ appliances, sport})",0.017520,0.043367,0.001963,0.112027,2.583230
34,"frozenset({ computers, country_yard})","frozenset({ appliances, electronics})",0.017520,0.040101,0.001479,0.084424,2.105265
35,"frozenset({ computers, appliances})","frozenset({ electronics, country_yard})",0.104244,0.006786,0.001479,0.014188,2.090805
36,"frozenset({ electronics, country_yard})","frozenset({ computers, appliances})",0.006786,0.104244,0.001479,0.217955,2.090805
37,"frozenset({ appliances, electronics})","frozenset({ computers, country_yard})",0.040101,0.017520,0.001479,0.036883,2.105265
38,"frozenset({ computers, appliances})","frozenset({ construction, electronics})",0.104244,0.007176,0.001743,0.016719,2.329990
39,"frozenset({ computers, construction})","frozenset({ appliances, electronics})",0.015626,0.040101,0.001743,0.111535,2.781345
40,"frozenset({ appliances, electronics})","frozenset({ computers, construction})",0.040101,0.015626,0.001743,0.043461,2.781345
41,"frozenset({ construction, electronics})","frozenset({ computers, appliances})",0.007176,0.104244,0.001743,0.242888,2.329990
42,"frozenset({ appliances, sport})","frozenset({ computers, construction})",0.043367,0.015626,0.001482,0.034178,2.187263
43,"frozenset({ computers, construction})","frozenset({ appliances, sport})",0.015626,0.043367,0.001482,0.094855,2.187263
44,"frozenset({ construction, appliances})",frozenset({ country_yard}),0.029694,0.089966,0.005555,0.187077,2.079428
45,"frozenset({ appliances, country_yard})",frozenset({ construction}),0.035102,0.074996,0.005555,0.158257,2.110212
46,frozenset({ construction}),"frozenset({ appliances, country_yard})",0.074996,0.035102,0.005555,0.074073,2.110212
47,frozenset({ country_yard}),"frozenset({ construction, appliances})",0.089966,0.029694,0.005555,0.061747,2.079428
48,"frozenset({ computers, country_yard})","frozenset({ construction, appliances})",0.017520,0.029694,0.001156,0.065962,2.221350
49,"frozenset({ computers, construction})","frozenset({ appliances, country_yard})",0.015626,0.035102,0.001156,0.073955,2.106864
50,"frozenset({ appliances, country_yard})","frozenset({ computers, construction})",0.035102,0.015626,0.001156,0.032922,2.106864
51,"frozenset({ construction, appliances})","frozenset({ computers, country_yard})",0.029694,0.017520,0.001156,0.038917,2.221350

Using the lift to compute association rules causes another problem. The lift is a measure that can be highly inflated when using really rare itemsets. This happens because the denominator is the product of the support measures of the two itemsets. In this situation probably the best strategy is to set minimum threshold values for both the measures.

In [5]:
s_purchases_rules = association_rules(s_purchases, metric="lift", min_threshold=2)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
s_purchases_rules = s_purchases_rules[s_purchases_rules["confidence"] > 0.10]
s_purchases_rules = s_purchases_rules.sort_values("lift", ascending=False)
s_purchases_rules = s_purchases_rules.reset_index(drop=True)
s_purchases_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ computers, medicine})","frozenset({ appliances, electronics})",0.016800,0.040101,0.001878,0.111776,2.787338
1,"frozenset({ computers, construction})","frozenset({ appliances, electronics})",0.015626,0.040101,0.001743,0.111535,2.781345
2,"frozenset({ computers, country_yard})","frozenset({ appliances, sport})",0.017520,0.043367,0.001963,0.112027,2.583230
3,"frozenset({ electronics, sport})","frozenset({ computers, appliances})",0.013089,0.104244,0.003505,0.267754,2.568525
4,"frozenset({ furniture, electronics})","frozenset({ computers, appliances})",0.005637,0.104244,0.001445,0.256267,2.458333
5,"frozenset({ furniture, sport})","frozenset({ computers, appliances})",0.005618,0.104244,0.001394,0.248183,2.380784
6,"frozenset({ medicine, electronics})","frozenset({ computers, appliances})",0.007675,0.104244,0.001878,0.244681,2.347185
7,"frozenset({ computers, electronics})","frozenset({ appliances, sport})",0.034643,0.043367,0.003505,0.101160,2.332649
8,"frozenset({ construction, electronics})","frozenset({ computers, appliances})",0.007176,0.104244,0.001743,0.242888,2.329990
9,"frozenset({ computers, medicine})","frozenset({ appliances, sport})",0.016800,0.043367,0.001686,0.100374,2.314514
10,"frozenset({ medicine, sport})","frozenset({ computers, appliances})",0.006997,0.104244,0.001686,0.241023,2.312099
11,"frozenset({ appliances, country_yard})",frozenset({ construction}),0.035102,0.074996,0.005555,0.158257,2.110212
12,"frozenset({ computers, appliances, electroni...",frozenset({ medicine}),0.016647,0.053695,0.001878,0.112809,2.100902
13,"frozenset({ electronics, country_yard})","frozenset({ computers, appliances})",0.006786,0.104244,0.001479,0.217955,2.090805
14,"frozenset({ construction, appliances})",frozenset({ country_yard}),0.029694,0.089966,0.005555,0.187077,2.079428
15,"frozenset({ electronics, sport})",frozenset({ medicine}),0.013089,0.053695,0.001432,0.109405,2.037509

### Conclusions

The rules above should suggest possible purchase patterns followed by the users. When an user buys one or more products of the antecedent section / sections, there is a reasonable possibility that he will buy one or more product also of the consequent section / sections.
The advised strategy is set as follows:
- Let's take as an example the first rule, so {computers, medicine} -> {electronics, appliances};
- Let's assume an user has already added to its basket one product from "computers" section and one from "medicine" section;
- After the user adds to the basket this last product, the page should show a fast link to the "electronics" section and one to the "appliances" section.

## Pattern mining on purchases and products

The purpose of this section is to find strong associations between purchases of products, in order to provide an efficient advise policy and encourage the user to buy more products.

In [6]:
with open("frequent_purchases.pkl", "rb") as f:  # "rb" = read binary
    purchases = pickle.load(f)

purchases = pd.DataFrame(purchases)

print("Number of frequent itemsets")
print(len(purchases))

Number of frequent itemsets
524

In [7]:
purchases_rules = association_rules(purchases, metric="confidence", min_threshold=0.4)
purchases_rules = purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
print("Association rules with minimum confidence level set to 0.4")
purchases_rules

Association rules with minimum confidence level set to 0.4

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,frozenset({214820233}),frozenset({214820261}),0.003407,0.005524,0.002283,0.670046,121.303101
1,frozenset({214820261}),frozenset({214820233}),0.005524,0.003407,0.002283,0.413303,121.303101
2,frozenset({214716710}),frozenset({214716707}),0.001928,0.003583,0.001212,0.628664,175.455247
3,frozenset({214834877}),frozenset({214834880}),0.010419,0.010328,0.004491,0.430983,41.728123
4,frozenset({214834880}),frozenset({214834877}),0.010328,0.010419,0.004491,0.434783,41.728123
5,frozenset({214826610}),frozenset({214834880}),0.009468,0.010328,0.004924,0.520066,50.353300
6,frozenset({214834880}),frozenset({214826610}),0.010328,0.009468,0.004924,0.476741,50.353300
7,frozenset({214826610}),frozenset({214834877}),0.009468,0.010419,0.004098,0.432836,41.541281
8,"frozenset({214834877, 214826610})",frozenset({214834880}),0.004098,0.010328,0.002371,0.578544,56.015167
9,"frozenset({214834877, 214834880})",frozenset({214826610}),0.004491,0.009468,0.002371,0.527972,55.764353
10,"frozenset({214826610, 214834880})",frozenset({214834877}),0.004924,0.010419,0.002371,0.481505,46.212300
11,frozenset({214833755}),frozenset({214834877}),0.002804,0.010419,0.001510,0.538634,51.695210
12,frozenset({214833755}),frozenset({214826610}),0.002804,0.009468,0.001212,0.432251,45.654291
13,frozenset({214829387}),frozenset({214826610}),0.002789,0.009468,0.001278,0.458333,48.409121
14,frozenset({214829387}),frozenset({214834880}),0.002789,0.010328,0.001206,0.432432,41.868505
15,frozenset({214829387}),frozenset({214834877}),0.002789,0.010419,0.001605,0.575450,55.228675
16,frozenset({214829865}),frozenset({214829861}),0.002299,0.003222,0.001203,0.523224,162.395280
17,frozenset({214829865}),frozenset({214829846}),0.002299,0.003191,0.001049,0.456284,143.012747
18,frozenset({214829885}),frozenset({214829878}),0.006020,0.021332,0.002773,0.460616,21.592854
19,"frozenset({214829885, 214829882})",frozenset({214829878}),0.001548,0.021332,0.001033,0.667343,31.283867
20,frozenset({214829887}),frozenset({214829878}),0.012800,0.021332,0.007289,0.569431,26.693924
21,frozenset({214831948}),frozenset({214829878}),0.007854,0.021332,0.004032,0.513395,24.067046
22,"frozenset({214831948, 214829882})",frozenset({214829878}),0.001737,0.021332,0.001275,0.734177,34.416948
23,frozenset({214831946}),frozenset({214829878}),0.008162,0.021332,0.004491,0.550212,25.792962
24,"frozenset({214831946, 214829882})",frozenset({214829878}),0.001950,0.021332,0.001366,0.700483,32.837426
25,"frozenset({214831946, 214829887})",frozenset({214829878}),0.001526,0.021332,0.001008,0.660494,30.962799
26,frozenset({214829882}),frozenset({214829878}),0.009207,0.021332,0.006089,0.661323,31.001685
27,"frozenset({214829882, 214829887})",frozenset({214829878}),0.002635,0.021332,0.002063,0.783075,36.709195
28,frozenset({214831950}),frozenset({214829885}),0.002933,0.006020,0.002267,0.773019,128.410719
29,frozenset({214835017}),frozenset({214835019}),0.006211,0.008001,0.002654,0.427199,53.390510
30,frozenset({214835109}),frozenset({214826990}),0.008560,0.006657,0.003457,0.403888,60.667860
31,frozenset({214826990}),frozenset({214835109}),0.006657,0.008560,0.003457,0.519340,60.667860
32,frozenset({214829765}),frozenset({214835167}),0.005919,0.008428,0.003850,0.650398,77.166655
33,frozenset({214835167}),frozenset({214829765}),0.008428,0.005919,0.003850,0.456781,77.166655
34,"frozenset({214835109, 214835167})",frozenset({214829765}),0.002129,0.005919,0.001109,0.520649,87.956255
35,"frozenset({214835109, 214829765})",frozenset({214835167}),0.001366,0.008428,0.001109,0.811494,96.279984
36,"frozenset({214835109, 214836932})",frozenset({214826990}),0.002113,0.006657,0.001127,0.533432,80.126578
37,"frozenset({214836932, 214826990})",frozenset({214835109}),0.001702,0.008560,0.001127,0.662362,77.375306
38,frozenset({214838227}),frozenset({214835109}),0.003991,0.008560,0.002449,0.613690,71.689619
39,frozenset({214838227}),frozenset({214826990}),0.003991,0.006657,0.001774,0.444532,66.772880
40,"frozenset({214835109, 214838227})",frozenset({214826990}),0.002449,0.006657,0.001256,0.512821,77.030479
41,"frozenset({214838227, 214826990})",frozenset({214835109}),0.001774,0.008560,0.001256,0.707965,82.702524
42,"frozenset({214836924, 214835167})",frozenset({214829765}),0.001881,0.005919,0.001212,0.644407,108.863476
43,"frozenset({214836924, 214829765})",frozenset({214835167}),0.001554,0.008428,0.001212,0.779798,92.519370
44,frozenset({214839971}),frozenset({214839973}),0.003238,0.006692,0.001322,0.408341,61.020119
45,frozenset({214839977}),frozenset({214839956}),0.001580,0.002751,0.001146,0.725646,263.787276
46,frozenset({214839956}),frozenset({214839977}),0.002751,0.001580,0.001146,0.416667,263.787276
47,frozenset({214838092}),frozenset({214837280}),0.002754,0.001664,0.001228,0.445838,267.876345
48,frozenset({214837280}),frozenset({214838092}),0.001664,0.002754,0.001228,0.737736,267.876345
49,frozenset({214837286}),frozenset({214838092}),0.002299,0.002754,0.001033,0.449454,163.199301
50,frozenset({214844355}),frozenset({214844370}),0.002792,0.005301,0.001244,0.445444,84.033810
51,frozenset({214835428}),frozenset({214835426}),0.002493,0.002343,0.001184,0.474811,202.681958
52,frozenset({214835426}),frozenset({214835428}),0.002343,0.002493,0.001184,0.505362,202.681958
53,frozenset({214845962}),frozenset({214846119}),0.003065,0.003121,0.001809,0.590164,189.068575
54,frozenset({214846119}),frozenset({214845962}),0.003121,0.003065,0.001809,0.579477,189.068575
55,frozenset({214848380}),frozenset({214848337}),0.001890,0.003680,0.001275,0.674419,183.246210
56,frozenset({214716707}),frozenset({214832604}),0.003583,0.002098,0.001539,0.429448,204.723192
57,frozenset({214832604}),frozenset({214716707}),0.002098,0.003583,0.001539,0.733533,204.723192

In [8]:
purchases_rules_no = association_rules(purchases, metric="lift", min_threshold=0.0000000001)
print("Number of association rules with no threshold value")
print(len(purchases_rules_no))
purchases_rules_l = association_rules(purchases, metric="lift", min_threshold=2)
print("Number of patterns with threshold value of the lift set equal to 1.5")
print(len(purchases_rules_l))

Number of association rules with no threshold value
216
Number of patterns with threshold value of the lift set equal to 1.5
216

# Conclusions

In this situation the confidence is a more accurate measure since the lift is highly inflated by not-so-frequent itemsets. This is easily showed by the fact that the number of association rules does not change with or without a normal threshold value for the lift (2 should already be a "good" association).

The advised strategy is to show a link / advertisement for the consequent product / products when the antecedent product / products are added to the basket.

In [9]:
purchases_rules = purchases_rules[["antecedents", "consequents", "antecedent support", "consequent support", "support", "confidence", "lift"]]
mono_associations = purchases_rules[(purchases_rules["antecedents"].apply(len) == 1) & (purchases_rules["consequents"].apply(len) == 1)]
multi_associations = purchases_rules[(purchases_rules["antecedents"].apply(len) > 1) | (purchases_rules["consequents"].apply(len) > 1)]

print(mono_associations.head())
print(multi_associations)

              antecedents             consequents  antecedent support  \
0  frozenset({214820233})  frozenset({214820261})            0.003407
1  frozenset({214820261})  frozenset({214820233})            0.005524
2  frozenset({214716710})  frozenset({214716707})            0.001928
3  frozenset({214834877})  frozenset({214834880})            0.010419
4  frozenset({214834880})  frozenset({214834877})            0.010328

   consequent support   support  confidence        lift
0            0.005524  0.002283    0.670046  121.303101
1            0.003407  0.002283    0.413303  121.303101
2            0.003583  0.001212    0.628664  175.455247
3            0.010328  0.004491    0.430983   41.728123
4            0.010419  0.004491    0.434783   41.728123
                          antecedents             consequents  \
8   frozenset({214834877, 214826610})  frozenset({214834880})
9   frozenset({214834877, 214834880})  frozenset({214826610})
10  frozenset({214826610, 214834880})  frozenset({214834877})
19  frozenset({214829885, 214829882})  frozenset({214829878})
22  frozenset({214831948, 214829882})  frozenset({214829878})
24  frozenset({214831946, 214829882})  frozenset({214829878})
25  frozenset({214831946, 214829887})  frozenset({214829878})
27  frozenset({214829882, 214829887})  frozenset({214829878})
34  frozenset({214835109, 214835167})  frozenset({214829765})
35  frozenset({214835109, 214829765})  frozenset({214835167})
36  frozenset({214835109, 214836932})  frozenset({214826990})
37  frozenset({214836932, 214826990})  frozenset({214835109})
40  frozenset({214835109, 214838227})  frozenset({214826990})
41  frozenset({214838227, 214826990})  frozenset({214835109})
42  frozenset({214836924, 214835167})  frozenset({214829765})
43  frozenset({214836924, 214829765})  frozenset({214835167})

    antecedent support  consequent support   support  confidence        lift
8             0.004098            0.010328  0.002371    0.578544   56.015167
9             0.004491            0.009468  0.002371    0.527972   55.764353
10            0.004924            0.010419  0.002371    0.481505   46.212300
19            0.001548            0.021332  0.001033    0.667343   31.283867
22            0.001737            0.021332  0.001275    0.734177   34.416948
24            0.001950            0.021332  0.001366    0.700483   32.837426
25            0.001526            0.021332  0.001008    0.660494   30.962799
27            0.002635            0.021332  0.002063    0.783075   36.709195
34            0.002129            0.005919  0.001109    0.520649   87.956255
35            0.001366            0.008428  0.001109    0.811494   96.279984
36            0.002113            0.006657  0.001127    0.533432   80.126578
37            0.001702            0.008560  0.001127    0.662362   77.375306
40            0.002449            0.006657  0.001256    0.512821   77.030479
41            0.001774            0.008560  0.001256    0.707965   82.702524
42            0.001881            0.005919  0.001212    0.644407  108.863476
43            0.001554            0.008428  0.001212    0.779798   92.519370

In [10]:
purchases_rules["pair"] = purchases_rules.apply(
    lambda r: tuple(sorted([
        next(iter(r["antecedents"])),
        next(iter(r["consequents"]))
    ])),
    axis=1
)
pair_counts = purchases_rules["pair"].value_counts()
asymmetric_pairs = pair_counts[pair_counts == 1]
print("Mono-directional relationships")
asymmetric_pairs

Mono-directional relationships

pair
(214716707, 214716710)    1
(214833755, 214834877)    1
(214826610, 214833755)    1
(214826610, 214829387)    1
(214829387, 214834880)    1
(214829387, 214834877)    1
(214829861, 214829865)    1
(214829846, 214829865)    1
(214829878, 214829887)    1
(214829885, 214831950)    1
(214835017, 214835019)    1
(214829765, 214835109)    1
(214835109, 214835167)    1
(214835109, 214836932)    1
(214826990, 214838227)    1
(214829765, 214836924)    1
(214835167, 214836924)    1
(214839971, 214839973)    1
(214837286, 214838092)    1
(214844355, 214844370)    1
(214848337, 214848380)    1
Name: count, dtype: int64

For an association rule {A} -> {B} that respects the confidence threshold value let's define it as:
- Bi-directional rule: if the relation {B} -> {A} also respects the confidence threshold value;
- Mono-directional rule: if the relation {B} -> {A} does not respect the confidence threshold value.

The last output shows all the mono-directional rules regarding purchases with only one product as antecedent (the first one) and only one product as consequent (the second one). The business strategy of above suggests to show the link / advertisement only when the first product is added to the basket, but another strategy could be implemented for the opposite relation.

Assuming the rule to be {A} -> {B}, let's assume that in general it is really likely to buy the two products together, but the customer is more likely to remember to buy product B after buying product A, but not to buy product A after buying product B. After implementing a correct A/B test to check for this hypothesis, an efficient strategy would be to show advertiments for both the directions, in order to increase purchases of the products together, independently of which one is bought first.

## Pattern mining on clicks in different sections

This section of the analysis aims to show the most frequent patterns in clicking products of different sections in the same session. The purpose for this is to show a link to a particular section when the user clicks on a product of another section, in order to push the user to buy more products.

In [2]:
with open("frequent_clicks_sections_2.pkl", "rb") as f:  # "rb" = read binary
    s_clicks = pickle.load(f)

s_clicks = pd.DataFrame(s_clicks)

print("Number of frequent sections")
print(len(s_clicks))

Number of frequent sections
933

In this situation the minimum support was set equal to 0.005 because the clicks are much more frequent

In [3]:
s_clicks_rules = association_rules(s_clicks, metric="confidence", min_threshold=0.5)
s_clicks_rules = s_clicks_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum confidence level set to 0.9")
s_clicks_rules

Association rules with minimum confidence level set to 0.9

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ electronics, computers})",frozenset({ appliances}),0.081344,0.535649,0.046854,0.576002,1.075334
1,frozenset({ furniture}),frozenset({ appliances}),0.128933,0.535649,0.068234,0.529223,0.988002
2,"frozenset({ electronics, furniture})",frozenset({ appliances}),0.030507,0.535649,0.019720,0.646410,1.206778
3,"frozenset({ electronics, furniture})",frozenset({ computers}),0.030507,0.433499,0.017631,0.577930,1.333176
4,"frozenset({ electronics, furniture, applianc...",frozenset({ computers}),0.019720,0.433499,0.013514,0.685312,1.580886
...,...,...,...,...,...,...,...
1627,"frozenset({ sport, appliances})",frozenset({ computers}),0.083310,0.433499,0.042063,0.504902,1.164714
1628,"frozenset({ electronics, sport})",frozenset({ appliances}),0.034614,0.535649,0.021049,0.608109,1.135274
1629,"frozenset({ electronics, sport})",frozenset({ computers}),0.034614,0.433499,0.020167,0.582628,1.344014
1630,"frozenset({ electronics, computers, sport})",frozenset({ appliances}),0.020167,0.535649,0.014624,0.725167,1.353810
1631,"frozenset({ electronics, sport, appliances})",frozenset({ computers}),0.021049,0.433499,0.014624,0.694782,1.602730

The clicks are more frequent than the purchases, consequently even with a confidence level set to 0.9 there are 166 association rules. As before, in such a situation, the confidence could be inflated by some really frequent sections (i.e. appliances just as before, with a support of 0.53). So using the lift could be an efficient strategy.

In [4]:
s_clicks_rules = association_rules(s_clicks, metric="lift", min_threshold=2)
s_clicks_rules = s_clicks_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum lift level set to 4")
s_clicks_rules

Association rules with minimum lift level set to 4

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ electronics, computers, applianc...",frozenset({ furniture}),0.046854,0.128933,0.013514,0.288430,2.237048
1,"frozenset({ furniture, appliances, computers})",frozenset({ electronics}),0.033792,0.188770,0.013514,0.399926,2.118592
2,"frozenset({ electronics, furniture})","frozenset({ computers, appliances})",0.030507,0.205260,0.013514,0.442992,2.158206
3,"frozenset({ electronics, appliances})","frozenset({ furniture, computers})",0.093973,0.057349,0.013514,0.143809,2.507596
4,"frozenset({ electronics, computers})","frozenset({ furniture, appliances})",0.081344,0.068234,0.013514,0.166136,2.434787
...,...,...,...,...,...,...,...
12271,frozenset({ sport}),"frozenset({ medicine, auto, appliances})",0.180245,0.002299,0.001012,0.005617,2.443375
12272,"frozenset({ electronics, computers})","frozenset({ sport, appliances})",0.081344,0.083310,0.014624,0.179784,2.158023
12273,"frozenset({ electronics, sport})","frozenset({ computers, appliances})",0.034614,0.205260,0.014624,0.422503,2.058384
12274,"frozenset({ computers, appliances})","frozenset({ electronics, sport})",0.205260,0.034614,0.014624,0.071248,2.058384
12275,"frozenset({ sport, appliances})","frozenset({ electronics, computers})",0.083310,0.081344,0.014624,0.175542,2.158023

Just as before for the purchases, the lift alone shows some problems too, being inflated by really rare sections. So the best strategy is using threshold values for both the measures.

In [6]:
s_clicks_rules = association_rules(s_clicks, metric="lift", min_threshold=2)
s_clicks_rules = s_clicks_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
s_clicks_rules = s_clicks_rules[s_clicks_rules["confidence"] > 0.60]
s_clicks_rules = s_clicks_rules.sort_values("lift", ascending=False)
s_clicks_rules = s_clicks_rules.reset_index(drop=True)
s_clicks_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ apparel, furniture, accessories,...","frozenset({ electronics, computers})",0.001543,0.081344,0.001021,0.661739,8.135062
1,"frozenset({ sport, accessories, appliances, ...","frozenset({ electronics, computers})",0.001785,0.081344,0.001135,0.635928,7.817754
2,"frozenset({ auto, furniture, appliances, co...","frozenset({ electronics, computers})",0.001741,0.081344,0.001101,0.632689,7.777929
3,"frozenset({ furniture, accessories, applianc...","frozenset({ electronics, computers})",0.002260,0.081344,0.001422,0.628970,7.732214
4,"frozenset({ furniture, accessories, applianc...","frozenset({ electronics, computers})",0.002030,0.081344,0.001277,0.628882,7.731136
...,...,...,...,...,...,...,...
409,"frozenset({ electronics, appliances, kids, ...",frozenset({ computers}),0.001153,0.433499,0.001005,0.871292,2.009906
410,"frozenset({ electronics, apparel, sport, co...",frozenset({ computers}),0.001351,0.433499,0.001175,0.869972,2.006862
411,"frozenset({ electronics, apparel, furniture,...",frozenset({ computers}),0.001178,0.433499,0.001024,0.869440,2.005635
412,"frozenset({ electronics, apparel, country_ya...",frozenset({ computers}),0.001174,0.433499,0.001020,0.869004,2.004629
413,"frozenset({ apparel, stationery, appliances,...",frozenset({ computers}),0.001229,0.433499,0.001066,0.867121,2.000284

### Conclusions

The results show itemsets with a lot of sections that do not seem correlated. Even with high threshold values for both the measures, the number of association rules computed is really big. Consequently we can assess that probably these results are not really reliable, but just the direct consequence of a wide navigation in the website of the company, maybe without a clear willing to buy certain products from different sections.

## Pattern mining on clicks and products

The purpose of this section is to find strong associations between clicks on products, in order to provide an efficient advise policy and encourage the user to buy more products.

In [7]:
with open("frequent_clicks.pkl", "rb") as f:  # "rb" = read binary
    clicks = pickle.load(f)

clicks = pd.DataFrame(clicks)

clicks_rules = association_rules(clicks, metric="confidence", min_threshold=0.2)
print(len(clicks_rules))

99

In [8]:
clicks_rules = association_rules(clicks, metric="confidence", min_threshold=0.4)
clicks_rules = clicks_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
print("Association rules with minimum confidence level set to 0.4")
clicks_rules

Association rules with minimum confidence level set to 0.4

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,frozenset({214838227}),frozenset({214835109}),0.003541,0.005359,0.001707,0.481891,89.930089
1,frozenset({214819762}),frozenset({214819760}),0.003582,0.004821,0.001717,0.479364,99.442240
2,frozenset({214826912}),frozenset({214828987}),0.002927,0.003162,0.001475,0.503956,159.377916
3,frozenset({214828987}),frozenset({214826912}),0.003162,0.002927,0.001475,0.466479,159.377916
4,frozenset({214834865}),frozenset({214827007}),0.002141,0.002877,0.001037,0.484193,168.298295
5,frozenset({214834865}),frozenset({214827005}),0.002141,0.003044,0.001014,0.473378,155.488926
6,frozenset({214827000}),frozenset({214827005}),0.001942,0.003044,0.001083,0.557798,183.218256
7,frozenset({214584992}),frozenset({214840595}),0.002341,0.001749,0.001010,0.431507,246.666364
8,frozenset({214840595}),frozenset({214584992}),0.001749,0.002341,0.001010,0.577393,246.666364
9,frozenset({214831948}),frozenset({214829878}),0.002635,0.013804,0.001185,0.449628,32.571783
10,frozenset({214835745}),frozenset({214600492}),0.005595,0.004489,0.002266,0.404967,90.209518
11,frozenset({214600492}),frozenset({214835745}),0.004489,0.005595,0.002266,0.504762,90.209518
12,frozenset({214835747}),frozenset({214835017}),0.005640,0.007213,0.003474,0.615919,85.390519
13,frozenset({214835017}),frozenset({214835747}),0.007213,0.005640,0.003474,0.481600,85.390519
14,frozenset({214587712}),frozenset({214835017}),0.003517,0.007213,0.001753,0.498480,69.108887
15,frozenset({214587712}),frozenset({214835747}),0.003517,0.005640,0.001573,0.447315,79.311538
16,"frozenset({214835747, 214587712})",frozenset({214835017}),0.001573,0.007213,0.001085,0.689694,95.618635
17,"frozenset({214835017, 214587712})",frozenset({214835747}),0.001753,0.005640,0.001085,0.618902,109.734960
18,frozenset({214831946}),frozenset({214829878}),0.002881,0.013804,0.001470,0.510204,36.960003
19,frozenset({214709792}),frozenset({214835752}),0.003160,0.003215,0.001781,0.563698,175.308472
20,frozenset({214835752}),frozenset({214709792}),0.003215,0.003160,0.001781,0.554017,175.308472
21,frozenset({214834880}),frozenset({214826610}),0.007425,0.008654,0.003378,0.454894,52.563810
22,"frozenset({214834877, 214826610})",frozenset({214834880}),0.002435,0.007425,0.001274,0.523043,70.443925
23,"frozenset({214834877, 214834880})",frozenset({214826610}),0.002569,0.008654,0.001274,0.495839,57.295036
24,frozenset({214832115}),frozenset({214832124}),0.002022,0.002727,0.001121,0.554185,203.195142
25,frozenset({214832124}),frozenset({214832115}),0.002727,0.002022,0.001121,0.410843,203.195142
26,frozenset({214829882}),frozenset({214829878}),0.003994,0.013804,0.002081,0.520963,37.739427
27,frozenset({214829765}),frozenset({214835167}),0.005106,0.005364,0.002136,0.418353,77.994857
28,frozenset({214836924}),frozenset({214836932}),0.005198,0.006762,0.002132,0.410212,60.661953
29,frozenset({214826977}),frozenset({214831959}),0.002400,0.003778,0.001028,0.428359,113.370817
30,frozenset({214829887}),frozenset({214829878}),0.004247,0.013804,0.002207,0.519715,37.648972
31,frozenset({214839971}),frozenset({214839973}),0.003419,0.008991,0.001630,0.476811,53.033042
32,frozenset({214848954}),frozenset({214848945}),0.002455,0.001637,0.001072,0.436865,266.848944
33,frozenset({214848945}),frozenset({214848954}),0.001637,0.002455,0.001072,0.655060,266.848944
34,frozenset({214827005}),frozenset({214827007}),0.003044,0.002877,0.001459,0.479228,166.572399
35,frozenset({214827007}),frozenset({214827005}),0.002877,0.003044,0.001459,0.507121,166.572399
36,frozenset({214826925}),frozenset({214827005}),0.002223,0.003044,0.001040,0.467949,153.705683
37,frozenset({214602598}),frozenset({214587317}),0.003454,0.004519,0.001445,0.418257,92.545713
38,frozenset({214829387}),frozenset({214826610}),0.003509,0.008654,0.001655,0.471574,54.491116
39,frozenset({214833755}),frozenset({214826610}),0.004218,0.008654,0.002111,0.500422,57.824631
40,frozenset({214829885}),frozenset({214829878}),0.002517,0.013804,0.001147,0.455768,33.016556
41,frozenset({214839373}),frozenset({214684513}),0.002136,0.004829,0.001211,0.567139,117.434023
42,frozenset({214832126}),frozenset({214832128}),0.002546,0.002147,0.001201,0.471659,219.722407
43,frozenset({214832128}),frozenset({214832126}),0.002147,0.002546,0.001201,0.559336,219.722407

In [10]:
clicks_rules_no = association_rules(clicks, metric="lift", min_threshold=0.0000000001)
print("Number of association rules with no threshold value")
print(len(clicks_rules_no))
clicks_rules_l = association_rules(clicks, metric="lift", min_threshold=2)
print("Number of patterns with threshold value of the lift set equal to 1.5")
print(len(clicks_rules_l))

Number of association rules with no threshold value
134
Number of patterns with threshold value of the lift set equal to 1.5
134

This data behaves in the same way of data about purchases. The lift is not really reliable, since it is inflated by the really rare products. Confidence gives more accurate and reliable association rules.

The advised strategy is to show a link / advertisement for the consequent product / products after clicking on the antecedent product / products.

In [11]:
clicks_rules = clicks_rules[["antecedents", "consequents", "antecedent support", "consequent support", "support", "confidence", "lift"]]
mono_associations = clicks_rules[(clicks_rules["antecedents"].apply(len) == 1) & (clicks_rules["consequents"].apply(len) == 1)]
multi_associations = clicks_rules[(clicks_rules["antecedents"].apply(len) > 1) | (clicks_rules["consequents"].apply(len) > 1)]

print(mono_associations.head())
print(multi_associations)

              antecedents             consequents  antecedent support  \
0  frozenset({214838227})  frozenset({214835109})            0.003541
1  frozenset({214819762})  frozenset({214819760})            0.003582
2  frozenset({214826912})  frozenset({214828987})            0.002927
3  frozenset({214828987})  frozenset({214826912})            0.003162
4  frozenset({214834865})  frozenset({214827007})            0.002141

   consequent support   support  confidence        lift
0            0.005359  0.001707    0.481891   89.930089
1            0.004821  0.001717    0.479364   99.442240
2            0.003162  0.001475    0.503956  159.377916
3            0.002927  0.001475    0.466479  159.377916
4            0.002877  0.001037    0.484193  168.298295
                          antecedents             consequents  \
16  frozenset({214835747, 214587712})  frozenset({214835017})
17  frozenset({214835017, 214587712})  frozenset({214835747})
22  frozenset({214834877, 214826610})  frozenset({214834880})
23  frozenset({214834877, 214834880})  frozenset({214826610})

    antecedent support  consequent support   support  confidence        lift
16            0.001573            0.007213  0.001085    0.689694   95.618635
17            0.001753            0.005640  0.001085    0.618902  109.734960
22            0.002435            0.007425  0.001274    0.523043   70.443925
23            0.002569            0.008654  0.001274    0.495839   57.295036

In [12]:
clicks_rules["pair"] = clicks_rules.apply(
    lambda r: tuple(sorted([
        next(iter(r["antecedents"])),
        next(iter(r["consequents"]))
    ])),
    axis=1
)
pair_counts = clicks_rules["pair"].value_counts()
asymmetric_pairs = pair_counts[pair_counts == 1]
asymmetric_pairs

pair
(214835109, 214838227)    1
(214819760, 214819762)    1
(214827007, 214834865)    1
(214827005, 214834865)    1
(214827000, 214827005)    1
(214829878, 214831948)    1
(214587712, 214835017)    1
(214587712, 214835747)    1
(214829878, 214831946)    1
(214826610, 214834880)    1
(214834877, 214834880)    1
(214826610, 214834877)    1
(214829878, 214829882)    1
(214829765, 214835167)    1
(214836924, 214836932)    1
(214826977, 214831959)    1
(214829878, 214829887)    1
(214839971, 214839973)    1
(214826925, 214827005)    1
(214587317, 214602598)    1
(214826610, 214829387)    1
(214826610, 214833755)    1
(214829878, 214829885)    1
(214684513, 214839373)    1
Name: count, dtype: int64

The strategy for the mono-directional rules is the same as before, but with clicks. Firstly, testing the hypothesis that the two products are likely to be bought together through an A/B test. If the test confirms the hypothesis, the strategy of before can be applied in both directions.